name: Update IIUMSchedule Cask

on:
  workflow_dispatch:

jobs:
  update_cask:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update cask
        run: |
          sudo apt install jq
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/iiumschedule/iium_schedule/releases/latest" | jq -r '.tag_name')
          LATEST_SHA=$(curl -sL "https://github.com/iiumschedule/iium_schedule/releases/download/v${LATEST_RELEASE}/IIUMSchedule.dmg" | sha256sum | cut -f 1 -d " ")

          echo "Latest release: $LATEST_RELEASE"
          echo "Latest SHA: $LATEST_SHA"

          sed -i "s/version .*/version \"${LATEST_RELEASE}\"/" Casks/iiumschedule.rb
          sed -i "s/sha256 .*/sha256 \"${LATEST_SHA}\"/" Casks/iiumschedule.rb

          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_MSG=":wrench: Update LocalSend cask to v${{ env.LATEST_RELEASE }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Casks/iiumschedule.rb
          git commit -m "$COMMIT_MSG"
          git push
